server:
  port: 8083

spring:
  redis:
    host: node1 #centos在windows中的hosts配置映射
    port: 6379
    jedis:
      pool:
        max-active: -1
    password: aaaa

logging:
  level:
    org.apache.zookeeper: off #关闭日志，可以更好观察控制台打印信息
